### PR TITLE
Add wallet monitoring

### PR DESCRIPTION
**Pull request by dylanschultzie**
This a rework of PFC's PR #41 to pull out the wallet monitoring functionality and clean it up a bit.

### CODE REVIEW

**Comment by dylanschultzie** [comment]
This has only been tested with a single wallet so far, will test 2 wallets shortly. 
Screenshot 2023-02-24 at 8 57 53 AM

**Comment by dylanschultzie** [comment]
Bah, switching to develop messed up the history.

**Comment by dylanschultzie** [comment]
Closing for now as it's too noisy

**Comment by dylanschultzie** [comment]
@joshlopes so, it works, but the problem is the loop in which it does the checks doesn't persist very long. If you run out of funds, it'll notify you every... 10 minutes?

**Comment by joshlopes** [comment]
@dylanschultzie That sounds a quick in-memory / temp file fix? for how long you want it to alert or in betweens? Sorry for not being too much help... I hate GO - doesn't make sense to me the structure so messy 🙈

**Pull request closed without merging**
