### PR TITLE
feat: add dead man's switch for td app itself

### PR DESCRIPTION
**Pull request by czarcas7ic**
I added a function that pings a user provided healthcheck URL at a user provided interval. This is useful to determine that the tenderduty application itself is live, and pagerduty notifications can be set if these healthcheck pings fail for a certain period of time.

I tested this locally and appears to function as intended.

### CODE REVIEW

**Review by blockpane — APPROVED** [review]

**Comment by alijnmerchant21** [comment]
@czarcas7ic @blockpane In the config file:

```
# Healthcheck settings (dead man's switch)
healthcheck:
  # Send pings to determine if the monitor is running?
  enabled: yes
  # URL to send pings to.
  ping_url: 
  # Rate in which pings are sent in seconds.
  ping_rate: 60
```

What does the ping url indicate? Does it refer to discord webhook for example, or it points to where node is running?

**Comment by czarcas7ic** [comment]
Whatever service you are using to determine that the tenderduty machine is up, not the actual node

**Comment by alijnmerchant21** [comment]
> Whatever service you are using to determine that the tenderduty machine is up, not the actual node

Thanks @czarcas7ic I'm using discord, so I added web-hook link. But it doesn't send any info. Any idea what could be wrong?

**Comment by czarcas7ic** [comment]
I would try something like better uptime and see if inputting the health check url works

**Pull request merged**
