### PR TITLE
Fix modal id not escaped in href

### PR DESCRIPTION
**Pull request by PikachuEXE**
Got error like this during testing
Only the one is `uk-toggle` is not escaped
image

### CODE REVIEW

**Review by blockpane — APPROVED** [review]

**Comment by blockpane** [comment]
Thanks for the PR!

**Comment by PikachuEXE** [comment]
You closed it instead of merging it 😨

**Comment by PikachuEXE** [comment]
Still not fixed 😵‍💫

**Comment by PikachuEXE** [comment]
This fix is missing in later versions...
e.g. https://github.com/blockpane/tenderduty/releases/tag/v2.2.1

**Pull request closed without merging**
