### PR TITLE
Feature : Support Valcons Address For ICS

### PR DESCRIPTION
**Pull request by jeongseup**
we need to support valcons type address for ics chains

code references
* https://github.com/cosmos/cosmos-sdk/blob/main/client/keys/parse.go#LL110C10-L110C10
*

### CODE REVIEW

**Comment by dylanschultzie** [comment]
Hey @Jeongseup thanks for the PR. It doesn't appear to work, however.

image

Using `valcons` neutronvalcons140l6y2gp3gxvay6qtn70re7z2s0gn57zxgsrkr

**Comment by dylanschultzie** [comment]
I can confirm that address is NOT missing blocks

Screenshot 2023-05-11 at 9 43 06 AM

**Comment by Jeongseup** [comment]
@dylanschultzie if your validator sent a assign key transaction in provider, cosmoshub-4, chnaged your valcon address.

**Comment by dylanschultzie** [comment]
@Jeongseup can you provide me an address that this does work with? The one you stated above doesn't work, either.

**Comment by Jeongseup** [comment]
> @Jeongseup can you provide me an address that this does work with? The one you stated above doesn't work, either.
working ! 

image


```bash
{
"address": "neutronvalcons1c5e86exd7jsyhcfqdejltdsagjfrvv8xhuwl2h",
"pub_key": {
"@type": "[/cosmos.crypto.ed25519.PubKey](http://lcd-neutron.cosmostation.io:20001/cosmos.crypto.ed25519.PubKey)",
"key": "FxSjsSvWPbw5NQczsh0+QRWqYTVauFJd/MateonbfO8="
},
"voting_power": "662764",
"proposer_priority": "11589650"
},
```

**Comment by reversesigh** [comment]
Where are you deriving `neutronvalcons1c5e86exd7jsyhcfqdejltdsagjfrvv8xhuwl2h` from? When checking the key that matches the correct valoper address, I'm seeing `neutronvalcons140l6y2gp3gxvay6qtn70re7z2s0gn57zxgsrkr`.

**Comment by reversesigh** [comment]
> @dylanschultzie
> 
> it is working with `neutronvalcons1c5e86exd7jsyhcfqdejltdsagjfrvv8xhuwl2h`
> 
> image
> 
> ```shell
> {
> "address": "neutronvalcons1c5e86exd7jsyhcfqdejltdsagjfrvv8xhuwl2h",
> "pub_key": {
> "@type": "[/cosmos.crypto.ed25519.PubKey](cosmos.crypto.ed25519.PubKey)",
> "key": "FxSjsSvWPbw5NQczsh0+QRWqYTVauFJd/MateonbfO8="
> },
> "voting_power": "662764",
> "proposer_priority": "11589650"
> },
> ```

How are you deriving the valcons key you are using for us?

When checking key against `--bech val` I see the valoper address that matches in Mintscan.
When checking key against `--bech cons` I see `neutronvalcons140l6y2gp3gxvay6qtn70re7z2s0gn57zxgsrkr` and not `neutronvalcons1c5e86exd7jsyhcfqdejltdsagjfrvv8xhuwl2h`

**Comment by dylanschultzie** [comment]
@Jeongseup interesting, it does appear to be working on the front end, but the back end is still throwing errors. Let me investigate more. I believe it has to do with what this PR is trying to solve: https://github.com/blockpane/tenderduty/pull/44

**Comment by Jeongseup** [comment]
change some logics for valcons address. and it can get uptime for validators!

**Comment by dylanschultzie** [comment]
Beauty, thanks @Jeongseup. I'll give it another go.

**Comment by dylanschultzie** [comment]
@Jeongseup is this still working for you?

**Comment by jeongseup** [comment]
Yeah It was still working well! What is wrong with you?

**Pull request merged**
