### PR TITLE
Feature : Modify tenderduty dashboard status about tendermint bn254 pubkey type for union chain

### PR DESCRIPTION
**Pull request by jeongseup**
## Purpose
Personally, so many validators who is operating chains in cosmos-sdk based chains want to use tenderduty for alerting their own validator nodes' uptime or something.

However, Its funtionality is not matched with chains which will be using BN254 types key such as Union Chain. 

Then, if you're a node operator in union testnet, you cannot see your node status like bottom.  

### dashboard & uptime
image
### logs
image

Because of it, I made a seond PR for tenderduty for modifying status and logs about tendermint. bn254 type and union chain.

I already knew it's not best way. But, It works! 

If you have a better way, I would welcome to modify this PR. Thanks.

### CODE REVIEW

**Comment by jeongseup** [comment]
## Explanation

1. Using valcons address : this is for correct querying signing info for uptime status

Screenshot 2023-12-14 at 1 52 43 PM

2. Using status by json-rpc : this is for get correct status loop for drawing dashboard 
image

---
Can you check this PR? @dylanschultzie

**Comment by jeongseup** [comment]
Have you seen this error to build Dockerfile?
```bash
Dockerfile:3
--------------------
   1 |     # 1st stage, build app
   2 |     FROM golang:1.19 as builder
   3 | >>> RUN apt-get update && apt-get -y upgrade && apt-get install -y upx
   4 |     COPY . /build/app
   5 |     WORKDIR /build/app
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get update && apt-get -y upgrade && apt-get install -y upx" did not complete successfully: exit code: 100
```

**Comment by dylanschultzie** [comment]
@Jeongseup pull the latest develop branch as there's a fix in it for that error. tl;dr: use `FROM golang:1.20.6-bullseye as builder
`

**Comment by jeongseup** [comment]
Thanks ! and then, Do you think I need to do something for this PR?

**Comment by dylanschultzie** [comment]
How are you using `json-rpc` for union? I don't see that available in the configs.

edit: nevermind

**Pull request merged**
